#!/usr/bin/env python3

def gen_macro(name: str, bits: int, struct_type: str, ctype: str) -> list[str]:
    args: list[str] = [f"T{i}" for i in range(bits-1, -1, -1)]
    args_str: str = ", ".join(args)

    def format_component(prefix: str, bits: int, ctype: str) -> list[str]:
        parts = [f"{prefix}(T{i}, {i})" for i in range(bits - 1, -1, -1)]

        parts_per_line: int = 4
        lines: list[str] = []
        for i in range(0, len(parts), parts_per_line):
            chunk = parts[i:i+parts_per_line]
            lines.append(" | ".join(chunk))

        indent = (4 + len(ctype) + 2) * " "
        if len(lines) == 1:
            return [f"({ctype})({lines[0]})"]
        else:
            res: list[str] = []
            res.append(f"({ctype})({lines[0]} | \\")
            for i in range(1, len(lines)):
                l = indent + lines[i]
                if i < len(lines):
                    l += " | \\"
                res.append(l)
            res.append(')')
            return res

    lcomp: str = '\n'.join(format_component("_TC48_TL", bits, ctype))
    hcomp: str = '\n'.join(format_component("_TC48_TH", bits, ctype))

    macro_start = f"#define TC48_{name.upper()}({args_str}) "
    struct_start = f"(({struct_type}){{ "

    total_len = len(macro_start) + len(struct_start)
    spaces = max(1, 80 - total_len)

    res: list[str] = []
    res.append(f"{macro_start}{struct_start}{' ' * spaces}\\")
    res.append(f"    {lcomp}, \\")
    res.append(f"    {hcomp}  \\")
    res.append("})")
    res.append("")
    res.append(f"#define TC48_{name.upper()}_ZERO (({struct_type}) {{ .l = 0, .h = 0 }})")
    res.append(f"#define TC48_{name.upper()}_EQL(A, B) ((((A).l) == ((B).l)) && (((A).h) == ((B).h)))")
    return res

def main() -> int:
    print("// NOTE: this file is auto-generated by scripts/gen_word_literals.py")
    print("//       do not modify this file directly")
    print("#pragma once")
    print()

    types: tuple = (
        ("doublet", 2, "tc48_doublet", "tc48_u8b"),
        ("triplet", 3, "tc48_triplet", "tc48_u8b"),
        ("quadruplet", 4, "tc48_quadruplet", "tc48_u8b"),
        ("tryte", 6, "tc48_tryte", "tc48_u8b"),
        ("quarter", 12, "tc48_quarter", "tc48_u16b"),
        ("half", 24, "tc48_half", "tc48_u32b"),
        ("word", 48, "tc48_word", "tc48_u64b"),
    )

    for name, bits, struct_type, ctype in types:
        lines: list[str] = gen_macro(name, bits, struct_type, ctype)
        print('\n'.join(lines))
        print()
    return 0

if __name__ == "__main__":
    exit(main())
