#!/usr/bin/env python3

def gen_macro(name, bits, struct_type, c_type):
    args = [f"t{i}" for i in range(bits-1, -1, -1)]
    arg_list = ", ".join(args)

    def format_component(prefix, bits, c_type):
        parts = [f"{prefix}(t{i}, {i})" for i in range(bits - 1, -1, -1)]

        parts_per_line = 4
        lines = []
        for i in range(0, len(parts), parts_per_line):
            chunk = parts[i:i+parts_per_line]
            lines.append(" | ".join(chunk))

        indent_size = 4 + len(c_type) + 2
        indent = " " * indent_size

        if len(lines) == 1:
            return f"({c_type})({lines[0]})"
        else:
            res = f"({c_type})({lines[0]} | \\\n"
            for i in range(1, len(lines)):
                l = indent + lines[i]
                if i < len(lines) - 1:
                    l += " | \\"
                res += l + "\n"
            return res.rstrip() + ")"

    l_comp = format_component("_TC48_TL", bits, c_type)
    h_comp = format_component("_TC48_TH", bits, c_type)

    macro_start = f"#define TC48_{name.upper()}({arg_list}) "
    struct_start = f"(({struct_type}){{ "

    # Try to align backslash roughly to column 80+
    total_len = len(macro_start) + len(struct_start)
    spaces = max(1, 80 - total_len)

    res = f"{macro_start}{struct_start}{' ' * spaces}\\\n"
    res += f"    {l_comp}, \\\n"
    res += f"    {h_comp}  \\\n"
    res += "})"
    res += "\n"
    res += f"#define TC48_{name.upper()}_ZERO (({struct_type}) {{ .l = 0, .h = 0 }})"
    return res

def main():
    print("// NOTE: this file is auto-generated by scripts/gen_word_literals.py")
    print("//       do not modify this file directly")
    print("#pragma once")
    print()

    types = [
        ("doublet", 2, "tc48_doublet", "tc48_u8b"),
        ("triplet", 3, "tc48_triplet", "tc48_u8b"),
        ("quadruplet", 4, "tc48_quadruplet", "tc48_u8b"),
        ("tryte", 6, "tc48_tryte", "tc48_u8b"),
        ("quarter", 12, "tc48_quarter", "tc48_u16b"),
        ("half", 24, "tc48_half", "tc48_u32b"),
        ("word", 48, "tc48_word", "tc48_u64b"),
    ]

    for name, bits, struct_type, c_type in types:
        print(gen_macro(name, bits, struct_type, c_type))
        print()

if __name__ == "__main__":
    main()
