#!/usr/bin/env python

def main() -> int:
    n_u32: int = 21
    n_u64: int = 41
    n_u128: int = 81
    
    content = []
    content.append("// NOTE: this file is auto-generated by scripts/pow3.py")
    content.append("//       do not modify this file directly")
    content.append("#include <tc48/pow3.h>")
    content.append("#include <stdint.h>")
    
    # 32-bit table
    content.append("const uint32_t tc48_pow3_u32[TC48_MAX_SAFE_TRITS_U32] = {")
    p = 1
    for _ in range(n_u32):
        content.append(f"    {p}U,")
        p *= 3
    content.append("};")
    
    # 64-bit table
    content.append("const uint64_t tc48_pow3_u64[TC48_MAX_SAFE_TRITS_U64] = {")
    p = 1
    for _ in range(n_u64):
        content.append(f"    {p}ULL,")
        p *= 3
    content.append("};")
    
    # 128-bit table
    content.append("const __uint128_t tc48_pow3_u128[TC48_MAX_SAFE_TRITS_U128] = {")
    p = 1
    for _ in range(n_u128):
        # format as (high << 64 | low) to avoid "error: "
        high = p >> 64
        low = p & 0xFFFFFFFFFFFFFFFF
        if high == 0:
            content.append(f"    (__uint128_t){low}ULL,")
        else:
            content.append(f"    ((__uint128_t){high}ULL << 64 | {low}ULL),")
        p *= 3
    content.append("};")
    
    print("\n".join(content))
    return 0

if __name__ == '__main__':
    exit(main())
