#!/usr/bin/env python

def main() -> int:
    n: int = 40 
    content = []
    content.append("// NOTE: this file is auto-generated by scripts/pow3.py")
    content.append("//       do not modify this file directly")
    content.append("#include <stdint.h>")
    content.append("#include <tc48/pow3.h>")
    content.append("const uint64_t tc48_pow3[TC48_MAX_SAFE_TRITS] = {")
    
    p = 1
    for _ in range(n):
        content.append(f"    {p}ULL,")
        p *= 3
    
    content.append("};")
    
    print("\n".join(content))
    return 0

if __name__ == '__main__':
    exit(main())
