FEATURES ?= tva
COMMA := ,
FEATURES_LIST := $(subst $(COMMA), ,$(FEATURES))

SUPPORTED_FEATURES := tva none

UNKNOWN_FEATURES := $(filter-out $(SUPPORTED_FEATURES),$(FEATURES_LIST))
ifneq ($(UNKNOWN_FEATURES),)
    $(warning unknown features: $(UNKNOWN_FEATURES))
endif

HAS_TVA := $(filter tva,$(FEATURES_LIST))

FEATURE_CFLAGS :=
FEATURE_OBJS_STATIC :=
FEATURE_OBJS_SHARED :=

ifeq ($(HAS_TVA),tva)
	FEATURE_CFLAGS      += -DTC48_CONFIG_TVA=1
	FEATURE_OBJS_STATIC  += $(TVA_OBJS_STATIC)
	FEATURE_OBJS_SHARED  += $(TVA_OBJS_SHARED)
endif
